import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import MainLayout from "@layouts/main";
import styles from '@styles/Home.module.css'
import {getAllRecipesForHome} from "../lib/api"
import { documentToReactComponents } from '@contentful/rich-text-react-renderer'


export default function Home({allPosts}) {
  return (
    <MainLayout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.grid}>
          {
            allPosts.length > 0 ? (
              allPosts.map((post) => (
                <div className={styles.card} key={post.sys.id}>
                  <div className={styles.details}>
                    <Link href={`recipes/${post.sys.id}`}>
                      <a>{post.title}</a>
                    </Link>
                    <div className={styles.imageHolder}>
                      <Image src={post.featuredImage.url} height="300" width="300"/>
                    </div>
                    <div>{post.excerpt}</div>
                  </div>
                </div>
              ))
            ) : (
              <div className={styles.card}>
                <p>No posts added!</p>
              </div>
            )
          }
        </div>  
      </div>
    </MainLayout>
  )
}

export async function getStaticProps({preview = false}){
  let allPosts = (await getAllRecipesForHome(preview))  ?? [];

  return {
      props: { preview, allPosts }
      
  }
  
}